### ISSUE TITLE
PSG Problem

### ISSUE THREAD

**Issue by JCGemX** [Potetobloke/PB_HDAddon_Bangers-And-Mash#2]
Your PSG2A1 Rifle and the "Personal Shield Generator" addon share the same loadout code, could you change it to "ps1" instead?

**Comment by tedthepraimortis** [comment]
[Fixed on my branch and will be merged when next available to.](https://github.com/tedthedragon/PB-Weps-Organized-Edition/commit/ba538c63261034fe67c30c500159523eef7c4176)

**Comment by Potetobloke** [comment]
ill do it later
